version: "3.8"
services:
  gamify:
    image: skilltree/skills-service:2.7.0
    container_name: gamify
    depends_on:
      - postgres_gamify
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROPS=spring.datasource.url=jdbc:postgresql://postgres_gamify:5432/skills,
        spring.datasource.username=skills,
        spring.datasource.password=skillsPassword
      - _JAVA_OPTIONS=-Ddebug=debug
  postgres_gamify:
    image: postgres:latest
    container_name: postgres_gamify
    environment:
      POSTGRES_USER: "skills"
      POSTGRES_PASSWORD: "skillsPassword"
      POSTGRES_DB: skills
    ports:
      - "5432:5432"
  gamify_authentication:
    container_name: gamify_authentication
    build:
      context: java-backend-example
    ports:
      - "8090:8090"
    depends_on:
    - gamify
    volumes:
      - ./java-backend-example/src:/usr/src/myapp/src