version: "3.8"
services:
  gamify:
    image: skilltree/skills-service:2.7.0
    container_name: gamify
    depends_on:
      - postgres_gamify
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROPS=spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB},
        spring.datasource.username=${POSTGRES_USER},
        spring.datasource.password=${POSTGRES_PASSWORD},
      - _JAVA_OPTIONS=-Ddebug=debug
  postgres_gamify:
    image: postgres:14
    container_name: postgres_gamify
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  gamify_authentication:
    container_name: gamify_authentication
    build:
      context: java-backend-example
    ports:
      - "8090:8090"
    environment:
      AUTHENTICATION_PORT: ${AUTHENTICATION_PORT}
      SERVICE_URL: ${SERVICE_URL}
      ROOT_USER_USERNAME: ${ROOT_USER_USERNAME}
      ROOT_USER_PASSWORD: ${ROOT_USER_PASSWORD}
    depends_on:
      - gamify
    restart: on-failure
    volumes:
      - ./java-backend-example/src:/usr/src/myapp/src
  gamify_dataimport:
    container_name: gamify_dataimport
    build:
      context: dataimporter
    environment:
      AUTHENTICATION_PORT: ${AUTHENTICATION_PORT}
      SERVICE_URL: ${SERVICE_URL}
      ROOT_USER_USERNAME: ${ROOT_USER_USERNAME}
      ROOT_USER_PASSWORD: ${ROOT_USER_PASSWORD}
    depends_on:
      - gamify
    restart: on-failure
    volumes:
      - ./dataimporter/src:/usr/src/myapp/src